title: Shintia Azzahra
logo: 
description:
  <strong>Electrical Enginnering</strong><br><br>
  Self-motivated, curious, diligent, and goal-oriented Data Scientist eager to apply my Python skills to solve business problems. With a background in science, I bring over 8 years of analytical thinking, data analysis, attention to detail, and problem-solving to the table.<br><br>
  <a href="https://www.linkedin.com/in/shintiaazzahra/">My LinkedIn</a>
